version: '3.3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile_${NGINX_VERSION}
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx_${NGINX_VERSION}/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/nginx_${NGINX_VERSION}/vhost:/etc/nginx/vhost"
      - type: bind
        source: ${APP_DIR}
        target: /myself
    links:
      - "php"
    depends_on:
      - php
    networks:
      - frontend
  php:
    build:
      context: ./php
      dockerfile: Dockerfile_${PHP_VERSION}
    expose:
      - "9000"
    volumes:
      - "./php/php_${PHP_VERSION}/php.ini:/usr/local/etc/php/php.ini"
      - "./php/php_${PHP_VERSION}/php-fpm.conf:/usr/local/etc/php-fpm.conf"
      - "./php/php_${PHP_VERSION}/php-fpm.d:/usr/local/etc/php-fpm.d"
      - type: bind
        source: ${APP_DIR}
        target: /myself
    links:
      - "mysql"
      - "redis"
    networks:
      - frontend
      - backend
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile_${MYSQL_VERSION}
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/mysql_${MYSQL_VERSION}/data:/var/lib/mysql"
      - "./mysql/mysql_${MYSQL_VERSION}/my.cnf:/etc/mysql/my.cnf"
      - "./mysql/mysql_${MYSQL_VERSION}/conf.d:/etc/mysql/conf.d"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - backend
  workspace:
    build:
      context: ./workspace
      dockerfile: Dockerfile_${PHP_VERSION}
    volumes:
      - "./workspace/php_${PHP_VERSION}/php.ini:/usr/local/etc/php/php.ini"
      - "./workspace/crontab:/etc/cron.d"
      - type: bind
        source: ${APP_DIR}
        target: /myself
    links:
     - "mysql"
     - "redis"
    networks:
      - backend
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile_${REDIS_VERSION}
    ports:
      - "6379:6379"
    volumes:
      - "./redis/redis_${REDIS_VERSION}/data:/data"
      - "./redis/redis_${REDIS_VERSION}/redis.conf:/etc/redis/redis.conf"
    networks:
      - backend
networks:
  frontend:
  backend:
