version: '3'
services:
	nginx:
		build: ./nginx
		ports: 
			- "5000:80"
		volumes:
			- ./workspace:/myself/
			- ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
			- ./nginx/conf/conf.d:/etc/nginx/conf.d
		links:
			- php
	php:
		build: ./php
		expose:
			- "9000"
		volumes:
			- ./php/conf:/usr/local/etc