version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./workspace:/myself/
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
    links:
      - php
    depends_on:
      - php
    networks:
      - ngx_php
  php:
    build: ./php
    expose:
      - 9000
    volumes:
      - ./php/php.ini:/usr/local/etc
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./workspace:/myself
    networks:
      - ngx_php
      - php_db
  db:
    build: ./mysql
    expose:
      - 3306
    networks:
      - php_db
    volumes:
      - 
    
volumes:
  - /myself
networks:
  - ngx_php
  - php_db
