FROM nginx:1.18.0

MAINTAINER running "A576236148946@126.com"

RUN apt update
RUN apt install curl -y \
	&& apt install procps -y \
	&& apt install vim -y 

COPY  nginx_1.18.0/vhost			/etc/nginx/vhost
COPY  nginx_1.18.0/nginx.conf	    /etc/nginx

WORKDIR /myself

volume /myself

CMD ["nginx"]
