FROM redis:6.0.4

MAINTAINER running "A576236148946@126.com"

RUN apt update \
    && apt install procps -y \
    && apt install curl -y \
    && apt install vim -y

COPY redis_6.0.4/redis.conf /etc/redis/redis.conf

CMD ["redis-server" , "/etc/redis/redis.conf"]