FROM php:7.4.6

MAINTAINER running "A576236148946@126.com"

RUN apt update
RUN apt install procps -y \
	&& apt install vim -y \
	&& apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
	&& apt install libsqlite3-dev  -y \
	&& apt install libzip-dev -y \
	&& apt install git -y \
	&& apt install cron -y \
	&& apt install rsyslog -y \
	&& apt install supervisor -y
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd
RUN docker-php-ext-install sockets
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install pdo_sqlite
RUN docker-php-ext-install bcmath
RUN pecl install redis-5.2.2 && docker-php-ext-enable redis
RUN pecl install zip-1.18.2 && docker-php-ext-enable zip
RUN pecl install swoole-4.5.1 && docker-php-ext-enable swoole
RUN mkdir -p /software \
    && curl -L -C - https://getcomposer.org/download/1.10.6/composer.phar -o /software/composer.phar \
    && mv /software/composer.phar /usr/local/bin/composer \
    && chmod 711 /usr/local/bin/composer

WORKDIR /myself

COPY start.sh /system/start.sh
COPY php_7.4.6/php.ini /usr/local/etc/php/php.ini

volume /myself

RUN sed -i 's/\r//g' /system/start.sh

CMD ["/bin/bash" , "/system/start.sh"]